#!/usr/bin/env bash
# Manages a process
file="manage_my_process"
pid="/var/run/my_process.pid"

if [[ $1 == "start" ]]
then
    touch "$pid"
    bash ./"$file" &
    echo "$!" > "$pid"
    echo "manage_my_process started"
elif [[ $1 == "stop" ]]
then
    kill "$(cat "$pid")"
    rm "$pid"
    echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]
then
    kill "$(cat "$pid")"
    rm "$pid"
    touch "$pid"
    bash ./"$file" &
    echo "$!" > "$pid"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
