#!/usr/bin/env bash
# I am invincible!!! when receiving a SIGTERM signal
# Print I am invicible when try to kill the process
# With the signal
while true
do
    echo "To infinity and beyond"
    trap 'echo "I am invincible!!!"' SIGTERM
    sleep 2
done
