#!/usr/bin/env bash
# Write a Bash script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.

i=1
while [ $i -lt 11 ]
do
    if [ $i = 9 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    let i+=1
done
